language: cpp
sudo: required
dist: trusty
     
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - CXX=g++-5
      compiler:
        - gcc
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - CXX=clang++-3.6
      compiler:
        - clang
    
install:
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y  # Qt-5.5
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt55base qt55x11extras qt55svg qt55quickcontrols libmuparser-dev

script:
  - source /opt/qt55/bin/qt55-env.sh
  - cmake . -DCMAKE_BUILD_TYPE=Debug
  - make
  - sudo make install

notifications:
  irc:
    channels:
      - "chat.freenode.net#albertlauncher"
    on_success: always # default: always
    on_failure: always # default: always
