os: linux
dist: focal
services:
  - docker

# https://www.digitalrooster.dev/news/travis-updated-docker/
script:
  - docker build .

notifications:
  irc:
    channels:
      - "chat.freenode.net#albertlauncher"
    on_success: change
    on_failure: change
    template:
      - "%{repository_name#%{build_number} (%{commit}) : %{message}\n\n%{build_url}"
