os: linux
dist: xenial
services:
  - docker

# https://www.digitalrooster.dev/news/travis-updated-docker/
script:
  - docker build .

notifications:
  irc:
    channels:
      - "chat.freenode.net#albertlauncher"
    on_success: change
    on_failure: always
